apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-status.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-status.labels" . | nindent 4 }}
data:
  ENV_NAME: {{ .Values.config.envName | quote }}
  ENV_TYPE: {{ .Values.config.envType | quote }}
  REGION: {{ .Values.config.region | quote }}
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  BASE_PATH: {{ .Values.config.basePath | quote }}
  SOURCES: {{ .Values.config.sources | quote }}
  ARGOCD_NAMESPACE: {{ .Values.config.argocdNamespace | quote }}
  ROOT_APP_NAME: {{ .Values.config.rootAppName | quote }}
  ARGOCD_UI_BASE: {{ .Values.config.argocdUIBase | quote }}
  IGNORE_GLOBS: {{ .Values.config.ignoreGlobs | quote }}
  CACHE_TTL_SECONDS: {{ .Values.config.cacheTTLSeconds | quote }}
  REFRESH_SECONDS: {{ .Values.config.refreshSeconds | quote }}
  NODE_STATS: {{ .Values.config.nodeStats | quote }}
  UNMANAGED: {{ .Values.config.unmanaged | quote }}
  UNMANAGED_IGNORE_NS: {{ .Values.config.unmanagedIgnoreNamespaces | quote }}
  PORT: {{ .Values.config.port | quote }}
